import React from 'react';
import { Link } from 'react-router-dom';
import { 
  Briefcase, 
  Users, 
  Sparkles, 
  FileText, 
  Plus, 
  TrendingUp, 
  Search, 
  Filter, 
  CheckCircle2, 
  Clock, 
  ChevronRight,
  ShieldCheck,
  User as UserIcon
} from 'lucide-react';
import { useAuth } from '../context/AuthContext';

export const RecruiterDashboard = () => {
  const { user } = useAuth();

  return (
    <div className="min-h-screen bg-grid-pattern pb-16">
      
      {/* Workspace Header Banner */}
      <div className="bg-slate-900/90 border-b border-slate-800">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
          <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
            
            <div className="flex items-center gap-4">
              <img
                src={user?.avatar_url || "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80"}
                alt={user?.full_name}
                className="w-16 h-16 rounded-2xl object-cover border-2 border-indigo-500/40 shadow-xl"
              />
              <div>
                <div className="flex items-center gap-2">
                  <h1 className="text-2xl font-bold text-white">{user?.full_name}</h1>
                  <span className="px-2.5 py-0.5 rounded-full text-xs font-semibold bg-indigo-500/20 text-indigo-300 border border-indigo-500/30 flex items-center gap-1">
                    <Briefcase className="w-3 h-3" /> HR Manager
                  </span>
                </div>
                <p className="text-sm text-slate-400 mt-1 flex items-center gap-2">
                  <span>{user?.company || "Apex Global Tech"}</span>
                  <span>•</span>
                  <span>{user?.headline || "Talent Acquisition Lead"}</span>
                </p>
              </div>
            </div>

            <div className="flex items-center gap-3">
              <Link
                to="/profile"
                className="px-4 py-2.5 text-xs font-semibold text-slate-300 bg-slate-800/80 hover:bg-slate-700 rounded-xl transition-all border border-slate-700 flex items-center gap-2"
              >
                <UserIcon className="w-4 h-4 text-purple-400" /> Account Settings
              </Link>
              <button
                disabled
                className="px-4 py-2.5 text-xs font-semibold text-white bg-indigo-600/50 cursor-not-allowed rounded-xl flex items-center gap-2 opacity-70"
                title="Enabled in Phase 2"
              >
                <Plus className="w-4 h-4" /> Post Job Opening (Phase 2)
              </button>
            </div>

          </div>
        </div>
      </div>

      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 pt-8 space-y-8">
        
        {/* Phase 1 Status Alert Card */}
        <div className="p-5 rounded-2xl bg-indigo-950/40 border border-indigo-500/30 flex items-start gap-4">
          <div className="w-10 h-10 rounded-xl bg-indigo-600/20 text-indigo-400 flex items-center justify-center shrink-0 mt-0.5">
            <ShieldCheck className="w-5 h-5" />
          </div>
          <div>
            <div className="flex items-center gap-2">
              <h3 className="text-sm font-bold text-white">HireAI Phase 1 Authentication & Session Valid</h3>
              <span className="text-[10px] px-2 py-0.5 rounded bg-emerald-500/20 text-emerald-300 border border-emerald-500/30 font-mono font-semibold">
                JWT Auth Active
              </span>
            </div>
            <p className="text-xs text-slate-400 mt-1 leading-relaxed">
              Your Recruiter workspace token has been generated by the FastAPI backend and verified against the MySQL database. Resume AI screening modules will activate in Phase 2.
            </p>
          </div>
        </div>

        {/* Analytics Statistics Cards Grid */}
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
          
          <div className="glass-panel p-5 rounded-2xl border border-slate-800 hover:border-indigo-500/30 transition-all">
            <div className="flex items-center justify-between">
              <span className="text-xs font-medium text-slate-400">Active Job Positions</span>
              <div className="w-8 h-8 rounded-lg bg-indigo-500/10 text-indigo-400 flex items-center justify-center">
                <Briefcase className="w-4 h-4" />
              </div>
            </div>
            <p className="text-3xl font-extrabold text-white mt-3 font-mono">12</p>
            <p className="text-[11px] text-emerald-400 mt-2 flex items-center gap-1">
              <TrendingUp className="w-3 h-3" /> +3 posted this month
            </p>
          </div>

          <div className="glass-panel p-5 rounded-2xl border border-slate-800 hover:border-purple-500/30 transition-all">
            <div className="flex items-center justify-between">
              <span className="text-xs font-medium text-slate-400">Total Applicants</span>
              <div className="w-8 h-8 rounded-lg bg-purple-500/10 text-purple-400 flex items-center justify-center">
                <Users className="w-4 h-4" />
              </div>
            </div>
            <p className="text-3xl font-extrabold text-white mt-3 font-mono">148</p>
            <p className="text-[11px] text-purple-400 mt-2">Across 12 open roles</p>
          </div>

          <div className="glass-panel p-5 rounded-2xl border border-slate-800 hover:border-cyan-500/30 transition-all">
            <div className="flex items-center justify-between">
              <span className="text-xs font-medium text-slate-400">AI Screened Resumes</span>
              <div className="w-8 h-8 rounded-lg bg-cyan-500/10 text-cyan-400 flex items-center justify-center">
                <Sparkles className="w-4 h-4" />
              </div>
            </div>
            <p className="text-3xl font-extrabold text-white mt-3 font-mono">114</p>
            <p className="text-[11px] text-cyan-400 mt-2">87% Average Match Index</p>
          </div>

          <div className="glass-panel p-5 rounded-2xl border border-slate-800 hover:border-amber-500/30 transition-all">
            <div className="flex items-center justify-between">
              <span className="text-xs font-medium text-slate-400">Shortlisted Candidates</span>
              <div className="w-8 h-8 rounded-lg bg-amber-500/10 text-amber-400 flex items-center justify-center">
                <CheckCircle2 className="w-4 h-4" />
              </div>
            </div>
            <p className="text-3xl font-extrabold text-white mt-3 font-mono">26</p>
            <p className="text-[11px] text-amber-400 mt-2">Ready for interview call</p>
          </div>

        </div>

        {/* Phase 2 Previews Section */}
        <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
          
          {/* Main Candidate Table Shell */}
          <div className="lg:col-span-2 glass-panel p-6 rounded-3xl border border-slate-800 space-y-6">
            <div className="flex items-center justify-between pb-4 border-b border-slate-800">
              <div>
                <h3 className="text-base font-bold text-white">Recent Candidate Applications</h3>
                <p className="text-xs text-slate-400">Screening queue ready for AI parsing</p>
              </div>
              <div className="flex items-center gap-2">
                <button className="p-2 rounded-xl bg-slate-900 border border-slate-800 text-slate-400 hover:text-white">
                  <Filter className="w-4 h-4" />
                </button>
              </div>
            </div>

            {/* Mock Application Queue Rows */}
            <div className="space-y-3">
              {[
                { name: 'David Miller', role: 'Full Stack Engineer', score: '94%', status: 'Top Match', color: 'text-emerald-400 bg-emerald-500/10 border-emerald-500/30' },
                { name: 'Elena Rostova', role: 'Backend Developer (Python)', score: '89%', status: 'Shortlisted', color: 'text-indigo-400 bg-indigo-500/10 border-indigo-500/30' },
                { name: 'Marcus Chen', role: 'DevOps / Cloud Specialist', score: '82%', status: 'Under Review', color: 'text-amber-400 bg-amber-500/10 border-amber-500/30' },
                { name: 'Sophia Taylor', role: 'AI / ML Research Engineer', score: '96%', status: 'Top Match', color: 'text-emerald-400 bg-emerald-500/10 border-emerald-500/30' }
              ].map((cand, idx) => (
                <div key={idx} className="p-4 rounded-2xl bg-slate-950/60 border border-slate-800/80 flex items-center justify-between hover:border-slate-700 transition-all">
                  <div className="flex items-center gap-3">
                    <div className="w-10 h-10 rounded-xl bg-indigo-500/20 text-indigo-300 font-bold flex items-center justify-center text-sm font-mono">
                      {cand.name.split(' ').map(n=>n[0]).join('')}
                    </div>
                    <div>
                      <p className="text-sm font-bold text-white">{cand.name}</p>
                      <p className="text-xs text-slate-400">{cand.role}</p>
                    </div>
                  </div>
                  <div className="flex items-center gap-4">
                    <div className="text-right hidden sm:block">
                      <p className="text-xs font-mono font-bold text-indigo-400">Match {cand.score}</p>
                      <span className={`text-[10px] px-2 py-0.5 rounded-full border font-semibold inline-block mt-0.5 ${cand.color}`}>
                        {cand.status}
                      </span>
                    </div>
                    <ChevronRight className="w-4 h-4 text-slate-500" />
                  </div>
                </div>
              ))}
            </div>

            <div className="text-center pt-2">
              <span className="text-xs text-slate-400 italic">
                Resume parsing engine & real-time screening algorithms will connect in Phase 2.
              </span>
            </div>

          </div>

          {/* Side Panel: Quick Actions & Phase Roadmap */}
          <div className="space-y-6">
            <div className="glass-panel p-6 rounded-3xl border border-slate-800 space-y-4">
              <h4 className="text-sm font-bold text-white flex items-center gap-2">
                <Sparkles className="w-4 h-4 text-indigo-400" /> Quick AI Actions
              </h4>
              <div className="space-y-2 text-xs">
                <div className="p-3 rounded-xl bg-slate-900/90 border border-slate-800 text-slate-300 flex items-center justify-between">
                  <span>Batch Resume Parser</span>
                  <span className="px-2 py-0.5 rounded bg-indigo-500/20 text-indigo-300 font-mono text-[10px]">Phase 2</span>
                </div>
                <div className="p-3 rounded-xl bg-slate-900/90 border border-slate-800 text-slate-300 flex items-center justify-between">
                  <span>Skill Weight Matrix</span>
                  <span className="px-2 py-0.5 rounded bg-purple-500/20 text-purple-300 font-mono text-[10px]">Phase 2</span>
                </div>
                <div className="p-3 rounded-xl bg-slate-900/90 border border-slate-800 text-slate-300 flex items-center justify-between">
                  <span>Candidate Score Export</span>
                  <span className="px-2 py-0.5 rounded bg-cyan-500/20 text-cyan-300 font-mono text-[10px]">Phase 3</span>
                </div>
              </div>
            </div>

            <div className="glass-panel p-6 rounded-3xl border border-slate-800 space-y-3">
              <h4 className="text-sm font-bold text-white">Active Session Details</h4>
              <div className="space-y-2 text-xs text-slate-400 font-mono">
                <div className="flex justify-between">
                  <span>User ID:</span>
                  <span className="text-white">#{user?.id}</span>
                </div>
                <div className="flex justify-between">
                  <span>Role:</span>
                  <span className="text-indigo-400 font-bold">{user?.role}</span>
                </div>
                <div className="flex justify-between">
                  <span>Email:</span>
                  <span className="text-slate-200">{user?.email}</span>
                </div>
                <div className="flex justify-between">
                  <span>JWT Token:</span>
                  <span className="text-emerald-400">Verified ✓</span>
                </div>
              </div>
            </div>

          </div>

        </div>

      </div>
    </div>
  );
};
